### ISSUE TITLE
error while executing linux-installer.sh

### ISSUE THREAD

**Issue by fettegans** [Streamers-Workshop/TrovoBot#203]
When executing the linux-installer.sh i get following messages:

```
linux-installer.sh: line 175: syntax error near unexpected token `elif'
linux-installer.sh: line 175: ` elif [[ ! -z "$(uname)" == "Mac" ]]; then'
```

Systeminformations:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by Rehkloos** [comment]
will look into  it

**Comment by Rehkloos** [comment]
@fettegans try this: https://raw.githubusercontent.com/Rehkloos/TrovoBot/6ae55c57ddcd0f154924d59b8370519a0ad0e9a7/tools/linux-installer.sh

**Comment by Bioblaze** [comment]
@Rehkloos did u fix it? make the PR so we can update it and close this.

**Comment by Rehkloos** [comment]
@Bioblaze asking OP to test to confirm

**Comment by fettegans** [comment]
Sorry guys, for some reason i didn't got an information about this thread...

The script is now working for me but i had to install yarn and unzip manually tho.

Thanks.
